# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent_to_renderer_list.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, '', 'agent_to_renderer_list.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import agent_to_renderer_pb2 as agent__to__renderer__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1c\x61gent_to_renderer_list.proto\x12\ta2ui.v1_0\x1a\x17\x61gent_to_renderer.proto"Q\n\x1a\x41gentToRendererMessageList\x12\x33\n\x08messages\x18\x01'
    b' \x03(\x0b\x32!.a2ui.v1_0.AgentToRendererMessageB>\n\rorg.a2ui.v1_0P\x01Z+a2ui.org/specification/v1_0/proto/a2uiprotob\x08\x65\x64itionsp\xe8\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'agent_to_renderer_list_pb2', _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = (
        b'\n\rorg.a2ui.v1_0P\001Z+a2ui.org/specification/v1_0/proto/a2uiproto'
    )
    _globals['_AGENTTORENDERERMESSAGELIST']._serialized_start = 68
    _globals['_AGENTTORENDERERMESSAGELIST']._serialized_end = 149
# @@protoc_insertion_point(module_scope)
