# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common_types.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, '', 'common_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x63ommon_types.proto\x12\ta2ui.v1_0\x1a\x1cgoogle/protobuf/struct.proto"\xbf\x01\n\x17\x41\x63\x63\x65ssibilityAttributes\x12\'\n\x05label\x18\x01'
    b' \x01(\x0b\x32\x18.a2ui.v1_0.DynamicString\x12-\n\x0b\x64\x65scription\x18\x02'
    b' \x01(\x0b\x32\x18.a2ui.v1_0.DynamicString\x12!\n\x04live\x18\x03'
    b' \x01(\x0e\x32\x13.a2ui.v1_0.LiveMode\x12)\n\x06hidden\x18\x04'
    b' \x01(\x0b\x32\x19.a2ui.v1_0.DynamicBoolean"\x86\x01\n\nExtensions\x12\x31\n\x06\x66ields\x18\x01'
    b' \x03(\x0b\x32!.a2ui.v1_0.Extensions.FieldsEntry\x1a\x45\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01'
    b' \x01(\t\x12%\n\x05value\x18\x02'
    b' \x01(\x0b\x32\x16.google.protobuf.Value:\x02\x38\x01">\n\x11\x43omponentMetadata\x12)\n\nextensions\x18\x01'
    b' \x01(\x0b\x32\x15.a2ui.v1_0.Extensions"\x9c\x01\n\x0f\x43omponentCommon\x12\n\n\x02id\x18\x01'
    b' \x01(\t\x12\x12\n\ncatalog_id\x18\x02 \x01(\t\x12\x39\n\raccessibility\x18\x03'
    b' \x01(\x0b\x32".a2ui.v1_0.AccessibilityAttributes\x12.\n\x08metadata\x18\x04'
    b' \x01(\x0b\x32\x1c.a2ui.v1_0.ComponentMetadata"(\n\x0fStaticChildList\x12\x15\n\rcomponent_ids\x18\x01'
    b' \x03(\t"7\n\x11\x43hildListTemplate\x12\x14\n\x0c\x63omponent_id\x18\x01'
    b' \x01(\t\x12\x0c\n\x04path\x18\x02'
    b' \x01(\t"\x81\x01\n\tChildList\x12\x31\n\x0bstatic_list\x18\x01'
    b' \x01(\x0b\x32\x1a.a2ui.v1_0.StaticChildListH\x00\x12\x30\n\x08template\x18\x02'
    b' \x01(\x0b\x32\x1c.a2ui.v1_0.ChildListTemplateH\x00\x42\x0f\n\rchildren_type"\x1b\n\x0b\x44\x61taBinding\x12\x0c\n\x04path\x18\x01'
    b' \x01(\t"\xaf\x02\n\x0c\x44ynamicValue\x12\x18\n\x0eliteral_string\x18\x01'
    b' \x01(\tH\x00\x12\x18\n\x0eliteral_number\x18\x02'
    b' \x01(\x01H\x00\x12\x19\n\x0fliteral_boolean\x18\x03'
    b' \x01(\x08H\x00\x12\x32\n\x0cliteral_list\x18\x04'
    b' \x01(\x0b\x32\x1a.google.protobuf.ListValueH\x00\x12\x31\n\x0eliteral_object\x18\x05'
    b' \x01(\x0b\x32\x17.google.protobuf.StructH\x00\x12.\n\x0c\x64\x61ta_binding\x18\x06'
    b' \x01(\x0b\x32\x16.a2ui.v1_0.DataBindingH\x00\x12\x30\n\rfunction_call\x18\x07'
    b' \x01(\x0b\x32\x17.a2ui.v1_0.FunctionCallH\x00\x42\x07\n\x05value"\x94\x01\n\rDynamicString\x12\x18\n\x0eliteral_string\x18\x01'
    b' \x01(\tH\x00\x12.\n\x0c\x64\x61ta_binding\x18\x02'
    b' \x01(\x0b\x32\x16.a2ui.v1_0.DataBindingH\x00\x12\x30\n\rfunction_call\x18\x03'
    b' \x01(\x0b\x32\x17.a2ui.v1_0.FunctionCallH\x00\x42\x07\n\x05value"\x94\x01\n\rDynamicNumber\x12\x18\n\x0eliteral_number\x18\x01'
    b' \x01(\x01H\x00\x12.\n\x0c\x64\x61ta_binding\x18\x02'
    b' \x01(\x0b\x32\x16.a2ui.v1_0.DataBindingH\x00\x12\x30\n\rfunction_call\x18\x03'
    b' \x01(\x0b\x32\x17.a2ui.v1_0.FunctionCallH\x00\x42\x07\n\x05value"\x96\x01\n\x0e\x44ynamicBoolean\x12\x19\n\x0fliteral_boolean\x18\x01'
    b' \x01(\x08H\x00\x12.\n\x0c\x64\x61ta_binding\x18\x02'
    b' \x01(\x0b\x32\x16.a2ui.v1_0.DataBindingH\x00\x12\x30\n\rfunction_call\x18\x03'
    b' \x01(\x0b\x32\x17.a2ui.v1_0.FunctionCallH\x00\x42\x07\n\x05value"\x1c\n\nStringList\x12\x0e\n\x06values\x18\x01'
    b' \x03(\t"\xb4\x01\n\x11\x44ynamicStringList\x12\x34\n\x13literal_string_list\x18\x01'
    b' \x01(\x0b\x32\x15.a2ui.v1_0.StringListH\x00\x12.\n\x0c\x64\x61ta_binding\x18\x02'
    b' \x01(\x0b\x32\x16.a2ui.v1_0.DataBindingH\x00\x12\x30\n\rfunction_call\x18\x03'
    b' \x01(\x0b\x32\x17.a2ui.v1_0.FunctionCallH\x00\x42\x07\n\x05value"$\n\x0e\x46unctionCommon\x12\x12\n\ncatalog_id\x18\x01'
    b' \x01(\t"\xa7\x01\n\x0c\x46unctionCall\x12\x0c\n\x04\x63\x61ll\x18\x01'
    b' \x01(\t\x12\x12\n\ncatalog_id\x18\x02 \x01(\t\x12/\n\x04\x61rgs\x18\x03'
    b' \x03(\x0b\x32!.a2ui.v1_0.FunctionCall.ArgsEntry\x1a\x44\n\tArgsEntry\x12\x0b\n\x03key\x18\x01'
    b' \x01(\t\x12&\n\x05value\x18\x02'
    b' \x01(\x0b\x32\x17.a2ui.v1_0.DynamicValue:\x02\x38\x01"H\n\x1cIndexSystemFunctionArguments\x12(\n\x06offset\x18\x01'
    b' \x01(\x0b\x32\x18.a2ui.v1_0.DynamicNumber"\x8b\x01\n\tCheckRule\x12.\n\x0c\x64\x61ta_binding\x18\x01'
    b' \x01(\x0b\x32\x16.a2ui.v1_0.DataBindingH\x00\x12\x30\n\rfunction_call\x18\x02'
    b' \x01(\x0b\x32\x17.a2ui.v1_0.FunctionCallH\x00\x12\x0f\n\x07message\x18\x03'
    b' \x01(\tB\x0b\n\tcondition"1\n\tCheckable\x12$\n\x06\x63hecks\x18\x01'
    b' \x03(\x0b\x32\x14.a2ui.v1_0.CheckRule"\xca\x01\n\x0b\x45ventAction\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12.\n\x0cuser_message\x18\x02'
    b' \x01(\x0b\x32\x18.a2ui.v1_0.DynamicString\x12\x34\n\x07\x63ontext\x18\x03'
    b' \x03(\x0b\x32#.a2ui.v1_0.EventAction.ContextEntry\x1aG\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01'
    b' \x01(\t\x12&\n\x05value\x18\x02'
    b' \x01(\x0b\x32\x17.a2ui.v1_0.DynamicValue:\x02\x38\x01"r\n\x06\x41\x63tion\x12\'\n\x05\x65vent\x18\x01'
    b' \x01(\x0b\x32\x16.a2ui.v1_0.EventActionH\x00\x12\x30\n\rfunction_call\x18\x02'
    b' \x01(\x0b\x32\x17.a2ui.v1_0.FunctionCallH\x00\x42\r\n\x0b\x61\x63tion_type"4\n\x10SurfaceContainer\x12\x11\n\tcomponent\x18\x01'
    b' \x01(\t\x12\r\n\x05\x63hild\x18\x02'
    b' \x01(\t".\n\rFunctionError\x12\x0c\n\x04\x63ode\x18\x01'
    b' \x01(\t\x12\x0f\n\x07message\x18\x02'
    b' \x01(\t"\x8c\x01\n\x10\x46unctionResponse\x12\x18\n\x10\x66unction_call_id\x18\x01'
    b" \x01(\t\x12'\n\x05value\x18\x02"
    b' \x01(\x0b\x32\x16.google.protobuf.ValueH\x00\x12)\n\x05\x65rror\x18\x03'
    b' \x01(\x0b\x32\x18.a2ui.v1_0.FunctionErrorH\x00\x42\n\n\x08response*g\n\x08LiveMode\x12\x19\n\x15LIVE_MODE_UNSPECIFIED\x10\x00\x12\x11\n\rLIVE_MODE_OFF\x10\x01\x12\x14\n\x10LIVE_MODE_POLITE\x10\x02\x12\x17\n\x13LIVE_MODE_ASSERTIVE\x10\x03\x42>\n\rorg.a2ui.v1_0P\x01Z+a2ui.org/specification/v1_0/proto/a2uiprotob\x08\x65\x64itionsp\xe8\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = (
        b'\n\rorg.a2ui.v1_0P\001Z+a2ui.org/specification/v1_0/proto/a2uiproto'
    )
    _globals['_EXTENSIONS_FIELDSENTRY']._loaded_options = None
    _globals['_EXTENSIONS_FIELDSENTRY']._serialized_options = b'8\001'
    _globals['_FUNCTIONCALL_ARGSENTRY']._loaded_options = None
    _globals['_FUNCTIONCALL_ARGSENTRY']._serialized_options = b'8\001'
    _globals['_EVENTACTION_CONTEXTENTRY']._loaded_options = None
    _globals['_EVENTACTION_CONTEXTENTRY']._serialized_options = b'8\001'
    _globals['_LIVEMODE']._serialized_start = 2892
    _globals['_LIVEMODE']._serialized_end = 2995
    _globals['_ACCESSIBILITYATTRIBUTES']._serialized_start = 64
    _globals['_ACCESSIBILITYATTRIBUTES']._serialized_end = 255
    _globals['_EXTENSIONS']._serialized_start = 258
    _globals['_EXTENSIONS']._serialized_end = 392
    _globals['_EXTENSIONS_FIELDSENTRY']._serialized_start = 323
    _globals['_EXTENSIONS_FIELDSENTRY']._serialized_end = 392
    _globals['_COMPONENTMETADATA']._serialized_start = 394
    _globals['_COMPONENTMETADATA']._serialized_end = 456
    _globals['_COMPONENTCOMMON']._serialized_start = 459
    _globals['_COMPONENTCOMMON']._serialized_end = 615
    _globals['_STATICCHILDLIST']._serialized_start = 617
    _globals['_STATICCHILDLIST']._serialized_end = 657
    _globals['_CHILDLISTTEMPLATE']._serialized_start = 659
    _globals['_CHILDLISTTEMPLATE']._serialized_end = 714
    _globals['_CHILDLIST']._serialized_start = 717
    _globals['_CHILDLIST']._serialized_end = 846
    _globals['_DATABINDING']._serialized_start = 848
    _globals['_DATABINDING']._serialized_end = 875
    _globals['_DYNAMICVALUE']._serialized_start = 878
    _globals['_DYNAMICVALUE']._serialized_end = 1181
    _globals['_DYNAMICSTRING']._serialized_start = 1184
    _globals['_DYNAMICSTRING']._serialized_end = 1332
    _globals['_DYNAMICNUMBER']._serialized_start = 1335
    _globals['_DYNAMICNUMBER']._serialized_end = 1483
    _globals['_DYNAMICBOOLEAN']._serialized_start = 1486
    _globals['_DYNAMICBOOLEAN']._serialized_end = 1636
    _globals['_STRINGLIST']._serialized_start = 1638
    _globals['_STRINGLIST']._serialized_end = 1666
    _globals['_DYNAMICSTRINGLIST']._serialized_start = 1669
    _globals['_DYNAMICSTRINGLIST']._serialized_end = 1849
    _globals['_FUNCTIONCOMMON']._serialized_start = 1851
    _globals['_FUNCTIONCOMMON']._serialized_end = 1887
    _globals['_FUNCTIONCALL']._serialized_start = 1890
    _globals['_FUNCTIONCALL']._serialized_end = 2057
    _globals['_FUNCTIONCALL_ARGSENTRY']._serialized_start = 1989
    _globals['_FUNCTIONCALL_ARGSENTRY']._serialized_end = 2057
    _globals['_INDEXSYSTEMFUNCTIONARGUMENTS']._serialized_start = 2059
    _globals['_INDEXSYSTEMFUNCTIONARGUMENTS']._serialized_end = 2131
    _globals['_CHECKRULE']._serialized_start = 2134
    _globals['_CHECKRULE']._serialized_end = 2273
    _globals['_CHECKABLE']._serialized_start = 2275
    _globals['_CHECKABLE']._serialized_end = 2324
    _globals['_EVENTACTION']._serialized_start = 2327
    _globals['_EVENTACTION']._serialized_end = 2529
    _globals['_EVENTACTION_CONTEXTENTRY']._serialized_start = 2458
    _globals['_EVENTACTION_CONTEXTENTRY']._serialized_end = 2529
    _globals['_ACTION']._serialized_start = 2531
    _globals['_ACTION']._serialized_end = 2645
    _globals['_SURFACECONTAINER']._serialized_start = 2647
    _globals['_SURFACECONTAINER']._serialized_end = 2699
    _globals['_FUNCTIONERROR']._serialized_start = 2701
    _globals['_FUNCTIONERROR']._serialized_end = 2747
    _globals['_FUNCTIONRESPONSE']._serialized_start = 2750
    _globals['_FUNCTIONRESPONSE']._serialized_end = 2890
# @@protoc_insertion_point(module_scope)
