# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: renderer_to_agent_list_wrapper.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'renderer_to_agent_list_wrapper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import renderer_to_agent_list_pb2 as renderer__to__agent__list__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$renderer_to_agent_list_wrapper.proto\x12\ta2ui.v1_0\x1a\x1crenderer_to_agent_list.proto\"U\n\x1aRendererToAgentListWrapper\x12\x37\n\x08messages\x18\x01 \x01(\x0b\x32%.a2ui.v1_0.RendererToAgentMessageListB>\n\rorg.a2ui.v1_0P\x01Z+a2ui.org/specification/v1_0/proto/a2uiprotob\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'renderer_to_agent_list_wrapper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rorg.a2ui.v1_0P\001Z+a2ui.org/specification/v1_0/proto/a2uiproto'
  _globals['_RENDERERTOAGENTLISTWRAPPER']._serialized_start=81
  _globals['_RENDERERTOAGENTLISTWRAPPER']._serialized_end=166
# @@protoc_insertion_point(module_scope)
