# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: renderer_capabilities.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, '', 'renderer_capabilities.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import catalog_definition_pb2 as catalog__definition__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1brenderer_capabilities.proto\x12\ta2ui.v1_0\x1a\x18\x63\x61talog_definition.proto"n\n\x16RendererCapabilitiesV1\x12\x1d\n\x15supported_catalog_ids\x18\x01'
    b' \x03(\t\x12\x35\n\x0finline_catalogs\x18\x02'
    b' \x03(\x0b\x32\x1c.a2ui.v1_0.CatalogDefinition"M\n\x14RendererCapabilities\x12\x35\n\x04v1_0\x18\x01'
    b' \x01(\x0b\x32!.a2ui.v1_0.RendererCapabilitiesV1R\x04v1.0B>\n\rorg.a2ui.v1_0P\x01Z+a2ui.org/specification/v1_0/proto/a2uiprotob\x08\x65\x64itionsp\xe8\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'renderer_capabilities_pb2', _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = (
        b'\n\rorg.a2ui.v1_0P\001Z+a2ui.org/specification/v1_0/proto/a2uiproto'
    )
    _globals['_RENDERERCAPABILITIESV1']._serialized_start = 68
    _globals['_RENDERERCAPABILITIESV1']._serialized_end = 178
    _globals['_RENDERERCAPABILITIES']._serialized_start = 180
    _globals['_RENDERERCAPABILITIES']._serialized_end = 257
# @@protoc_insertion_point(module_scope)
