# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: renderer_data_model.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'renderer_data_model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19renderer_data_model.proto\x12\ta2ui.v1_0\x1a\x1cgoogle/protobuf/struct.proto\"\xac\x01\n\x11RendererDataModel\x12\x0f\n\x07version\x18\x01 \x01(\t\x12<\n\x08surfaces\x18\x02 \x03(\x0b\x32*.a2ui.v1_0.RendererDataModel.SurfacesEntry\x1aH\n\rSurfacesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct:\x02\x38\x01\x42>\n\rorg.a2ui.v1_0P\x01Z+a2ui.org/specification/v1_0/proto/a2uiprotob\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'renderer_data_model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rorg.a2ui.v1_0P\001Z+a2ui.org/specification/v1_0/proto/a2uiproto'
  _globals['_RENDERERDATAMODEL_SURFACESENTRY']._loaded_options = None
  _globals['_RENDERERDATAMODEL_SURFACESENTRY']._serialized_options = b'8\001'
  _globals['_RENDERERDATAMODEL']._serialized_start=71
  _globals['_RENDERERDATAMODEL']._serialized_end=243
  _globals['_RENDERERDATAMODEL_SURFACESENTRY']._serialized_start=171
  _globals['_RENDERERDATAMODEL_SURFACESENTRY']._serialized_end=243
# @@protoc_insertion_point(module_scope)
