# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: renderer_to_agent.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 35, 1, '', 'renderer_to_agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_types_pb2 as common__types__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17renderer_to_agent.proto\x12\ta2ui.v1_0\x1a\x12\x63ommon_types.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto";\n\x0e\x41\x63tionMetadata\x12)\n\nextensions\x18\x01'
    b' \x01(\x0b\x32\x15.a2ui.v1_0.Extensions"\xef\x01\n\x12\x41\x63tionEventMessage\x12\x0c\n\x04name\x18\x01'
    b' \x01(\t\x12\x14\n\x0cuser_message\x18\x02 \x01(\t\x12\x12\n\nsurface_id\x18\x03'
    b' \x01(\t\x12\x1b\n\x13source_component_id\x18\x04'
    b' \x01(\t\x12-\n\ttimestamp\x18\x05'
    b' \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12(\n\x07\x63ontext\x18\x06'
    b' \x01(\x0b\x32\x17.google.protobuf.Struct\x12+\n\x08metadata\x18\x07'
    b' \x01(\x0b\x32\x19.a2ui.v1_0.ActionMetadata"x\n\x18\x43\x61llAgentFunctionMessage\x12\x12\n\nsurface_id\x18\x01'
    b' \x01(\t\x12\x18\n\x10\x66unction_call_id\x18\x02'
    b' \x01(\t\x12.\n\rcall_function\x18\x03'
    b' \x01(\x0b\x32\x17.a2ui.v1_0.FunctionCall"b\n\x1fRendererFunctionResponseMessage\x12?\n\x1arenderer_function_response\x18\x01'
    b' \x01(\x0b\x32\x1b.a2ui.v1_0.FunctionResponse"\xdf\x01\n\x15ValidationFailedError\x12\x33\n\x04\x63ode\x18\x01'
    b' \x01(\x0e\x32%.a2ui.v1_0.ValidationFailedError.Code\x12\x12\n\nsurface_id\x18\x02'
    b' \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04'
    b' \x01(\t"^\n\x04\x43ode\x12\x14\n\x10\x43ODE_UNSPECIFIED\x10\x00\x12\x15\n\x11VALIDATION_FAILED\x10\x01\x12\x14\n\x10UNALLOWED_PARENT\x10\x02\x12\x13\n\x0fUNALLOWED_CHILD\x10\x03"\x93\x01\n\x0cGenericError\x12\x0c\n\x04\x63ode\x18\x01'
    b' \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\nsurface_id\x18\x03'
    b' \x01(\tH\x00\x12\x1a\n\x10\x66unction_call_id\x18\x04'
    b' \x01(\tH\x00\x12(\n\x07\x64\x65tails\x18\x05'
    b' \x01(\x0b\x32\x17.google.protobuf.StructB\x08\n\x06target"\x94\x01\n\x14RendererErrorMessage\x12<\n\x10validation_error\x18\x01'
    b' \x01(\x0b\x32'
    b' .a2ui.v1_0.ValidationFailedErrorH\x00\x12\x30\n\rgeneric_error\x18\x02'
    b' \x01(\x0b\x32\x17.a2ui.v1_0.GenericErrorH\x00\x42\x0c\n\nerror_type"\xad\x02\n\x16RendererToAgentMessage\x12\x0f\n\x07version\x18\x01'
    b' \x01(\t\x12/\n\x06\x61\x63tion\x18\x02'
    b' \x01(\x0b\x32\x1d.a2ui.v1_0.ActionEventMessageH\x00\x12\x42\n\x13\x63\x61ll_agent_function\x18\x03'
    b' \x01(\x0b\x32#.a2ui.v1_0.CallAgentFunctionMessageH\x00\x12P\n\x1arenderer_function_response\x18\x04'
    b' \x01(\x0b\x32*.a2ui.v1_0.RendererFunctionResponseMessageH\x00\x12\x30\n\x05\x65rror\x18\x05'
    b' \x01(\x0b\x32\x1f.a2ui.v1_0.RendererErrorMessageH\x00\x42\t\n\x07messageB>\n\rorg.a2ui.v1_0P\x01Z+a2ui.org/specification/v1_0/proto/a2uiprotob\x08\x65\x64itionsp\xe8\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'renderer_to_agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = (
        b'\n\rorg.a2ui.v1_0P\001Z+a2ui.org/specification/v1_0/proto/a2uiproto'
    )
    _globals['_ACTIONMETADATA']._serialized_start = 121
    _globals['_ACTIONMETADATA']._serialized_end = 180
    _globals['_ACTIONEVENTMESSAGE']._serialized_start = 183
    _globals['_ACTIONEVENTMESSAGE']._serialized_end = 422
    _globals['_CALLAGENTFUNCTIONMESSAGE']._serialized_start = 424
    _globals['_CALLAGENTFUNCTIONMESSAGE']._serialized_end = 544
    _globals['_RENDERERFUNCTIONRESPONSEMESSAGE']._serialized_start = 546
    _globals['_RENDERERFUNCTIONRESPONSEMESSAGE']._serialized_end = 644
    _globals['_VALIDATIONFAILEDERROR']._serialized_start = 647
    _globals['_VALIDATIONFAILEDERROR']._serialized_end = 870
    _globals['_VALIDATIONFAILEDERROR_CODE']._serialized_start = 776
    _globals['_VALIDATIONFAILEDERROR_CODE']._serialized_end = 870
    _globals['_GENERICERROR']._serialized_start = 873
    _globals['_GENERICERROR']._serialized_end = 1020
    _globals['_RENDERERERRORMESSAGE']._serialized_start = 1023
    _globals['_RENDERERERRORMESSAGE']._serialized_end = 1171
    _globals['_RENDERERTOAGENTMESSAGE']._serialized_start = 1174
    _globals['_RENDERERTOAGENTMESSAGE']._serialized_end = 1475
# @@protoc_insertion_point(module_scope)
