# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sample.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'sample.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import agent_to_renderer_pb2 as agent__to__renderer__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\x12\ta2ui.v1_0\x1a\x17\x61gent_to_renderer.proto\"g\n\rCatalogSample\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x33\n\x08messages\x18\x03 \x03(\x0b\x32!.a2ui.v1_0.AgentToRendererMessageB>\n\rorg.a2ui.v1_0P\x01Z+a2ui.org/specification/v1_0/proto/a2uiprotob\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rorg.a2ui.v1_0P\001Z+a2ui.org/specification/v1_0/proto/a2uiproto'
  _globals['_CATALOGSAMPLE']._serialized_start=52
  _globals['_CATALOGSAMPLE']._serialized_end=155
# @@protoc_insertion_point(module_scope)
